config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get 'english', to: 'pages#homeen'
  get 'portuguese', to: 'pages#homept'
  get 'download_pt', to: 'downloads#download_cv_pt'
  get 'download_en', to: 'downloads#download_cv_en'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  def download_cv_en
    send_file "#{Rails.root}/app/assets/docs/CVLucasEN2020.pdf", type: "application/pdf", x_sendfile: true
  end

  def download_cv_pt
    send_file "#{Rails.root}/app/assets/docs/CVLucasPT2020.pdf", type: "application/pdf", x_sendfile: true
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CV Lucas Padilha</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <%= favicon_link_tag %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
      AOS.init();
    </script>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container homepage">
  <div class="row">
    <div class="col-sm-12">
      <h1 id="myname">Lucas <span class="white">Padilha</span></h1>
    </div>
  </div>
</div>


<div class="row">
  <div class="col-sm-12 options">
    <h3 id="enoption">Select Language</h3>
  </div>
  <div class="col-sm-12 options">
    <h6 id="ptoption">Selecione o idioma</h6>
  </div>
</div>

<div class="container languages">
  <div class="row">

    <div class="col-sm-12 col-md-6 language">
      <%= link_to english_path do %>
        <%= image_tag('enflag.png', :alt => "english",:width => "100%", :height => "100%", :id => "portugueseflag", onClick: "myFunction()") %>
      <% end %>
    </div>

    <div class="col-sm-12 col-md-6 language">
      <%= link_to portuguese_path do %>
        <%= image_tag('ptflag.png', :alt => "portuguese", :width => "100%", :height => "100%", :id => "englishflag") %>
      <% end %>
    </div>

    <script>
      function myFunction () {
        let timerInterval
        Swal.fire({
          title: 'Auto close alert!',
          html: 'I will close in <b></b> milliseconds.',
          timer: 2000,
          timerProgressBar: true,
          onBeforeOpen: () => {
            Swal.showLoading()
            timerInterval = setInterval(() => {
              const content = Swal.getContent()
              if (content) {
                const b = content.querySelector('b')
                if (b) {
                  b.textContent = Swal.getTimerLeft()
                }
              }
            }, 100)
          },
          onClose: () => {
            clearInterval(timerInterval)
          }
        }).then((result) => {
          /* Read more about handling dismissals below */
          if (result.dismiss === Swal.DismissReason.timer) {
            console.log('I was closed by the timer')
          }
        })
      }
    </script>

  </div>

</div>

<%# <div class="container downloads">
  <div class="row download">
    <div class="col-sm-12m download">
      <h3 id="downloaden">Or just Download PDF format</h3>
    </div>
    <div class="col-sm-12 download">
      <h6 id="downloadpt">Ou apenas faça o Download em PDF</h6>
    </div>
    <div class="col-sm-12" id="linkpdf">
      <button id="buttondownloaden">
        <%= link_to "Download #{image_tag("enflag.png", :id => "miniflagen", :height => "20%", :width => "20%", :style => "margin-bottom: 2%;")}".html_safe, download_en_path, :style => "margin-bottom: 2%;" %>
      <%# </button>
      <button id="buttondownloadpt">
        <%= link_to "Download #{image_tag("ptflag.png", :id => "miniflagpt", :height => "20%", :width => "20%", :style => "margin-bottom: 2%;")}".html_safe, download_pt_path, :style => "margin-bottom: 2%;" %>
      <%# </button>
    </div>
  </div>
</div> %> 